# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-31 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bour', '0002_auto_20190531_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
